services:
  postgres:
    image: postgres:16
    container_name: apt_postgres
    environment:
      POSTGRES_DB: aptdb
      POSTGRES_USER: apt
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata

    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Docker_Test/db/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apt -d aptdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: apt_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aptfinder.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  pgadmin_data:
